language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
services:
  - "mongodb"
sudo: false
#before_install:
#  - npm i
script:
  - npm test
#after_success:
#  - npm run report-coverage
branches:
  only:
    - master